#!/bin/tcsh

echo "Upgrade to latest BookKeepr version"
echo "==================================="
if ( -e ./dist/BookKeepr2.jar ) then
	echo "We appear to be in a bookkeepr directory..."
	echo "Downloading new code"
	wget http://www.atnf.csiro.au/people/Michael.Keith/bookkeepr/BookKeepr.tar.gz
	if ( $? == 0) then
		echo "Got a file"
	else
		echo "Could not download the tarball"
		exit 1
	endif
	echo "Unpacking"
	tar -C .. -xvzf BookKeepr.tar.gz
	echo "Done!"
else

endif
